// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpDhQkfNxvQCKshsvAR6NzJL8Z_OOjA98',
    appId: '1:198083572394:web:610c261065678c18f556d3',
    messagingSenderId: '198083572394',
    projectId: 'calorie-tracker-sila-69d95',
    authDomain: 'calorie-tracker-sila-69d95.firebaseapp.com',
    storageBucket: 'calorie-tracker-sila-69d95.firebasestorage.app',
    measurementId: 'G-5PB74X4C3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY3MfzxW3Z1ZFl3UKnhXaF66mdj4jEz4c',
    appId: '1:198083572394:android:12d05a66fec7d4b0f556d3',
    messagingSenderId: '198083572394',
    projectId: 'calorie-tracker-sila-69d95',
    storageBucket: 'calorie-tracker-sila-69d95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9HA3rkbdFVW7VZ7BZz7iunhURkpzP9so',
    appId: '1:198083572394:ios:090c75d276648fc1f556d3',
    messagingSenderId: '198083572394',
    projectId: 'calorie-tracker-sila-69d95',
    storageBucket: 'calorie-tracker-sila-69d95.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9HA3rkbdFVW7VZ7BZz7iunhURkpzP9so',
    appId: '1:198083572394:ios:090c75d276648fc1f556d3',
    messagingSenderId: '198083572394',
    projectId: 'calorie-tracker-sila-69d95',
    storageBucket: 'calorie-tracker-sila-69d95.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpDhQkfNxvQCKshsvAR6NzJL8Z_OOjA98',
    appId: '1:198083572394:web:f55ff888e877cd9ef556d3',
    messagingSenderId: '198083572394',
    projectId: 'calorie-tracker-sila-69d95',
    authDomain: 'calorie-tracker-sila-69d95.firebaseapp.com',
    storageBucket: 'calorie-tracker-sila-69d95.firebasestorage.app',
    measurementId: 'G-66JD88WNVC',
  );
}
